import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import React from 'react'
import { Providers } from './providers'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
}

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode
}>) {
    return (
        <Providers>
            <html lang="en">
                <head>
                    <meta
                        name="theme-color"
                        content="#ecd96f"
                        media="(prefers-color-scheme: light)"
                    />
                    <meta
                        name="theme-color"
                        content="#000"
                        media="(prefers-color-scheme: dark)"
                    />
                </head>
                <body className={inter.className}>{children}</body>
            </html>
        </Providers>
    )
}
